### ISSUE TITLE
Does it allow same domain signup?

### ISSUE THREAD

**Issue by leonardo2204** [MohammedNoureldin/frappe-oidc-extended#1]
Hi, @MohammedNoureldin, thanks for the plugin!
I'm not sure if I understand the "Automatically creates users from trusted identity providers even if signup is disabled in the site." part. Does this mean ANY social login is allowed or does it mean only a custom domain (similar to retool) is allowed?

eg. My domain is leonardo2204.com:

- Login with joao@leonardo2204.com -> Allowed
- Login with joao@gmail.com -> Not allowed

Is that so? 
Thanks

**Comment by MohammedNoureldin** [comment]
Hi!

Your example is correct.

Only custom providers added using this plugin can create new users if does not exist.

**Comment by leonardo2204** [comment]
Hi again, I've configured this way, but people trying to login with @nexforce.co domain cannot.
Am I missing something?

Thanks!

![Screenshot 2023-09-27 at 15 20 11](https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/1509421/5be96d56-9b4d-4a2c-abd8-1d2fc58fb3bb)

**Comment by MohammedNoureldin** [comment]
Hi, @leonardo2204,

Are you using google? I have tested this with my own KeyCloak server.

What is the error you get? Or what does the log say?

**Comment by leonardo2204** [comment]
Hey, @MohammedNoureldin,
Yep, I'm using Google. I'm able to log in when I add the user in the user section. Unfortunately, the log does not show anything. I'm getting this error:
Can I help you showing some other config?

![image (9)](https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/1509421/10d6a811-2edc-4a74-9c58-05c5dfd9abb9)


Thanks

**Comment by MohammedNoureldin** [comment]
What is the call back you are setting in your provider configuration?

**Comment by leonardo2204** [comment]
Hi, @MohammedNoureldin,

Sorry for the long reply. I have changed the redirect callback as you said, but now I'm facing a new error:

```
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "env/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7feaac308490>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.comhttps', port=443): Max retries exceeded with url: //accounts.google.com/o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feaac308490>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/oidc_extended/oidc_extended/callback.py", line 63, in custom
    token_response = requests.post(
  File "env/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.comhttps', port=443): Max retries exceeded with url: //accounts.google.com/o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feaac308490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

My config:

```
MariaDB [_c6b4dfc4d011fd4e]> select * from `tabSocial Login Key`\G;
*************************** 1. row ***************************
                 name: google
             creation: 2023-09-25 19:34:20.813435
             modified: 2023-09-25 19:34:20.813435
          modified_by: Administrator
                owner: Administrator
            docstatus: 0
                  idx: 0
  enable_social_login: 1
social_login_provider: Google
            client_id: ***.apps.googleusercontent.com
        provider_name: Google
        client_secret: ***********************************
                 icon: /assets/frappe/icons/social/google.svg
             base_url: https://www.googleapis.com
        authorize_url: https://accounts.google.com/o/oauth2/auth
     access_token_url: https://accounts.google.com/o/oauth2/token
         redirect_url: /api/method/oidc_extended.callback.custom/google
         api_endpoint: oauth2/v2/userinfo
      custom_base_url: 0
    api_endpoint_args: NULL
        auth_url_data: {"scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email", "response_type": "code"}
     user_id_property: NULL
           _user_tags: NULL
            _comments: NULL
              _assign: NULL
            _liked_by: NULL
```

And my API service:

![Screenshot 2023-10-06 at 16 40 34](https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/1509421/c4935e13-25c1-46bc-a264-ddd86a1e642f)
![Screenshot 2023-10-06 at 16 41 25](https://github.com/MohammedNoureldin/frappe-oidc-extended/assets/1509421/ced977e0-903c-42f7-b6a3-bcfddafb8b0c)

Am I missing something here?

Thanks again

**Comment by MohammedNoureldin** [comment]
I am not sure, but take a look on this. This setup for the original *social media login* works for me:

```
    {
        "name": "keycloak",
        "enable_social_login": 1,
        "social_login_provider": "Custom",
        "client_id": "erpnext",
        "provider_name": "keycloak",
        "client_secret": "{{ erpnext_idp_client_secret }}",
        "icon": "",
        "base_url": "https://idp.{{ domain_name }}/realms/{{ keycloak_realm }}",
        "authorize_url": "/protocol/openid-connect/auth",
        "access_token_url": "/protocol/openid-connect/token",
        "redirect_url": "/api/method/oidc_extended.callback.custom/keycloak",
        "api_endpoint": "https://idp.{{ domain_name }}/realms/{{ keycloak_realm }}/protocol/openid-connect/userinfo",
        "custom_base_url": 1,
        "auth_url_data": "{\"response_type\": \"code\", \"scope\": \"openid profile email\"}",
        "user_id_property": "preferred_username",
        "doctype": "Social Login Key"
    }

```

Notice the last part of your `redirect_url` must match the name of your provider:

        "redirect_url": "/api/method/oidc_extended.callback.custom/keycloak",

**Comment by MohammedNoureldin** [comment]
I updated the read me and added an example. Please let me know if you got any further.

**Comment by MohammedNoureldin** [comment]
Because of lack of activity I will close this, feel free to reopen it if needed.
